---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: grafana
  name: grafana
spec:
  ports:
  - name: grafana-grafana-metrics
    port: 3000
    targetPort: 3000
  - name: http
    port: 80
    targetPort: 3000
  selector:
    name: grafana
