---
apiVersion: v1
data:
  grafana.ini: |
    [analytics]
    reporting_enabled = false
    [auth.anonymous]
    enabled = true
    org_role = Admin
    [explore]
    enabled = true
    [server]
    http_port = 3000
    root_url = {{.Values.grafana_root_url}}
    [users]
    default_theme = light
kind: ConfigMap
metadata:
  name: grafana-config
