---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: prometheus
  name: prometheus
spec:
  ports:
  - name: prometheus-http-metrics
    port: 9090
    targetPort: 9090
  - name: http
    port: 80
    targetPort: 9090
  selector:
    name: prometheus
