apiVersion: v1
data:
  index.html: |
    <html>
      <head><title>Admin</title></head>
      <body>
        <h1>Admin</h1>
        <ul>
          <li><a href="/grafana">Grafana</a></li>

    <li><a href="/prometheus">Prometheus</a></li>

        </ul>
      </body>
    </html>
  nginx.conf: |-
    {{`worker_processes     5;  ## Default: 1
    error_log            /dev/stderr;
    pid                  /tmp/nginx.pid;
    worker_rlimit_nofile 8192;

    events {
      worker_connections  4096;  ## Default: 1024
    }

    http {
      default_type application/octet-stream;
      log_format   main '$remote_addr - $remote_user [$time_local]  $status '
        '"$request" $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';
      access_log   /dev/stderr  main;
      sendfile     on;
      tcp_nopush   on;
      resolver     kube-dns.kube-system.svc.cluster.local;
      server {
        listen 80;
        location ~ ^/grafana(/?)(.*)$ {
    proxy_pass      http://grafana.default.svc.cluster.local/$2$is_args$args;
    proxy_set_header    Host $host;
    proxy_set_header    X-Real-IP $remote_addr;
    proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header    X-Forwarded-Proto $scheme;
    proxy_set_header    X-Forwarded-Host $http_host;
    # Allow websocket connections https://www.nginx.com/blog/websocket-nginx/
    proxy_set_header    Upgrade $http_upgrade;
    proxy_set_header    Connection "Upgrade";
    }

    location ~ ^/prometheus(/?)(.*)$ {
    proxy_pass      http://prometheus.default.svc.cluster.local/prometheus/$2$is_args$args;
    proxy_set_header    Host $host;
    proxy_set_header    X-Real-IP $remote_addr;
    proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header    X-Forwarded-Proto $scheme;
    proxy_set_header    X-Forwarded-Host $http_host;
    }

        location ~ /(index.html)? {
          root /etc/nginx;
        }
      }
    }
    `}}
kind: ConfigMap
metadata:
  name: nginx-config
