apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-frontend
spec:
  minReadySeconds: 10
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: query-frontend
  template:
    metadata:
      labels:
        name: query-frontend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                name: query-frontend
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - -frontend.max-cache-freshness=10m
        - -frontend.memcached.hostname=memcached-frontend.{{.Values.namespace}}.svc.cluster.local
        - -frontend.memcached.service=memcached-client
        - -frontend.memcached.timeout=500ms
        - -limits.per-user-override-config=/etc/cortex/overrides.yaml
        - -log.level=debug
        - -querier.align-querier-with-step=true
        - -querier.cache-results=true
        - -querier.compress-http-responses=true
        - -querier.split-queries-by-interval=24h
        - -server.grpc-max-recv-msg-size-bytes=104857600
        - -server.http-write-timeout=1m
        - -store.max-query-length=12000h
        - -target=query-frontend
        image: cortexproject/cortex:v1.1.0
        imagePullPolicy: IfNotPresent
        name: query-frontend
        ports:
        - containerPort: 80
          name: http-metrics
        - containerPort: 9095
          name: grpc
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          limits:
            memory: 1200Mi
          requests:
            cpu: "2"
            memory: 600Mi
        volumeMounts:
        - mountPath: /etc/cortex
          name: overrides
      volumes:
      - configMap:
          name: overrides
        name: overrides
