apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: consul-sidekick
  namespace: '{{`.Values.namespace`}}'
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  resources:
  - pods
  - replicasets
  verbs:
  - get
  - list
  - watch
