---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: consul
  template:
    metadata:
      annotations:
        consul-hash: e56ef6821a3557604caccaf6d5820239
      labels:
        name: consul
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                name: consul
            topologyKey: kubernetes.io/hostname
          - labelSelector:
              matchLabels:
                name: ingester
            namespaces:
            - {{.Values.namespace}}
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - agent
        - -ui
        - -server
        - -client=0.0.0.0
        - -config-file=/etc/config/consul-config.json
        - -bootstrap-expect=1
        - -ui-content-path=/{{.Values.namespace}}/consul/
        env:
        - name: CHECKPOINT_DISABLE
          value: "1"
        image: consul:1.5.3
        imagePullPolicy: IfNotPresent
        name: consul
        ports:
        - containerPort: 8300
          name: server
        - containerPort: 8301
          name: serf
        - containerPort: 8400
          name: client
        - containerPort: 8500
          name: api
        resources:
          requests:
            cpu: "4"
            memory: 4Gi
        volumeMounts:
        - mountPath: /etc/config
          name: consul
        - mountPath: /consul/data/
          name: data
      - args:
        - --namespace=$(POD_NAMESPACE) - --pod-name=$(POD_NAME)
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: weaveworks/consul-sidekick:master-f18ad13
        imagePullPolicy: IfNotPresent
        name: sidekick
        volumeMounts:
        - mountPath: /etc/config
          name: consul
        - mountPath: /consul/data/
          name: data
      - args:
        - --web.listen-address=:8000
        - --statsd.mapping-config=/etc/config/mapping
        image: prom/statsd-exporter:v0.12.2
        imagePullPolicy: IfNotPresent
        name: statsd-exporter
        ports:
        - containerPort: 8000
          name: http-metrics
        volumeMounts:
        - mountPath: /etc/config
          name: consul
        - mountPath: /consul/data/
          name: data
      - args:
        - --consul.server=localhost:8500
        - --web.listen-address=:9107
        - --consul.timeout=1s
        - --no-consul.health-summary
        - --consul.allow_stale
        image: prom/consul-exporter:v0.5.0
        imagePullPolicy: IfNotPresent
        name: consul-exporter
        ports:
        - containerPort: 9107
          name: http-metrics
        volumeMounts:
        - mountPath: /etc/config
          name: consul
        - mountPath: /consul/data/
          name: data
      serviceAccount: consul-sidekick
      volumes:
      - configMap:
          name: consul
        name: consul
      - emptyDir:
          medium: Memory
        name: data
