---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: consul-sidekick
  namespace: {{.Values.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: consul-sidekick
subjects:
- kind: ServiceAccount
  name: consul-sidekick
  namespace: {{.Values.namespace}}
