---
apiVersion: v1
data:
  config.yaml: |
    configs:
      - chunks:
            period: {{(index .Values.schema 0).chunks.period}} prefix: {{(index .Values.schema 0).chunks.prefix}}
        from: {{(index .Values.schema 0).from}}
        index:
            period: {{(index .Values.schema 0).index.period}} prefix: {{(index .Values.schema 0).index.prefix}}
        object_store: {{(index .Values.schema 0).object_store}} schema: {{(index .Values.schema 0).schema}}
        store: {{(index .Values.schema 0).store}}
kind: ConfigMap
metadata:
  name: schema-{{.Values.schemaID}}
