---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: querier
  name: querier
spec:
  ports:
  - name: querier-http-metrics
    port: 80
    targetPort: 80
  - name: querier-grpc
    port: 9095
    targetPort: 9095
  selector:
    name: querier
