apiVersion: v1
kind: Service
metadata:
  labels:
    name: ingester
  name: ingester
spec:
  ports:
  - name: ingester-http-metrics
    port: 80
    targetPort: 80
  - name: ingester-grpc
    port: 9095
    targetPort: 9095
  selector:
    name: ingester
