apiVersion: v1
kind: Service
metadata:
  labels:
    name: query-frontend
  name: query-frontend
spec:
  ports:
  - name: query-frontend-http-metrics
    port: 80
    targetPort: 80
  - name: query-frontend-grpc
    port: 9095
    targetPort: 9095
  selector:
    name: query-frontend
